### ISSUE TITLE
AttributeError: 'Name' object has no attribute 'arg'

### ISSUE THREAD

**Issue by abachm** [JBKahn/flake8-print#25]
When upgrading to latest version of flake8-print (3.0.0) and using flake8 (3.5.0) I get the above error

```
[anders:~/tmp] [e] 7s $ flake8 -j 1 e/
Traceback (most recent call last):
  File "/home/anders/tmp/e/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/anders/tmp/e/local/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/anders/tmp/e/local/lib/python2.7/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/home/anders/tmp/e/local/lib/python2.7/site-packages/flake8/main/application.py", line 384, in _run
    self.run_checks()
  File "/home/anders/tmp/e/local/lib/python2.7/site-packages/flake8/main/application.py", line 310, in run_checks
    self.file_checker_manager.run()
  File "/home/anders/tmp/e/local/lib/python2.7/site-packages/flake8/checker.py", line 321, in run
    self.run_serial()
  File "/home/anders/tmp/e/local/lib/python2.7/site-packages/flake8/checker.py", line 305, in run_serial
    checker.run_checks()
  File "/home/anders/tmp/e/local/lib/python2.7/site-packages/flake8/checker.py", line 579, in run_checks
    self.run_ast_checks()
  File "/home/anders/tmp/e/local/lib/python2.7/site-packages/flake8/checker.py", line 493, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/home/anders/tmp/e/local/lib/python2.7/site-packages/flake8_print.py", line 88, in run
    parser.visit(self.tree)
  File "/usr/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
  File "/usr/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/home/anders/tmp/e/local/lib/python2.7/site-packages/flake8_print.py", line 49, in visit_FunctionDef
    if arg.arg in PRINT_FUNCTION_NAMES:
AttributeError: 'Name' object has no attribute 'arg'
```

**Comment by JBKahn** [comment]
I'll release a fix when I get to work. Must have missed something in my unit and integration tests. I'll use a getattr. Thanks for reporting it!

**Comment by JBKahn** [comment]
Hmm I'm on 27 on my machine and cannot reproduce it. Can you provide the version of python2.7 you're using?

**Comment by JBKahn** [comment]
Or a code snippet it's crashing on

**Comment by abachm** [comment]
$ python --version
Python 2.7.14

I have a virtual env with only flake8 + flake8-print installed and then running flake8 on that virtual env crashes it

**Comment by JBKahn** [comment]
identified, seems to work locally. Will release a hotfix.

**Comment by JBKahn** [comment]
shipped
